FITLTS/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from django.contrib import admin

import LTSFactories
import views

# load on startup
admin.autodiscover()
LTSFactories.setup_module() 

urlpatterns = patterns('',
	url(r'^index/$', views.home_page, name='home_page'),
	url(r'^calculator/$', views.calculator_page, name='calculator_page'),
	url(r'^calculator/', include('LTSTasks.urls', namespace='ltstasks')),
	url(r'^overview/$', views.alg_overview_page, name='alg_overview_page'),
	url(r'^library/$', views.library_page, name='library_page'),	
	url(r'^summary/', include('LTSSummary.urls', namespace='ltssummary')),
#	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^/?$', RedirectView.as_view(url=reverse_lazy('home_page'))),
)

LTSSummary/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView

from LTSSummary import views

urlpatterns = patterns('',
	url(r'^(?P<group_id>[A-Za-z0-9_-]+)$', views.summary, name='summary'),
	url(r'^(?P<group_id>[A-Za-z0-9_-]+)/pdf$', views.summary_pdf, name='pdf')
)

LTSSummary/models/renderers.py
from django import http
from django.shortcuts import render
from django.template.loader import get_template
from django.template import Context
import xhtml2pdf.pisa as pisa
import cStringIO as StringIO
import cgi
import numpy as np

from LTSAlgorithms.models import ParamVisitor

class RendererBase(object):
	"""Base class for renderers."""
	def __init__(self, task_group):
		self.group = task_group
	
	def strvector(self, matrix):
		"""Transforms matrix into readable double vector."""
		m = matrix.get_matrix_trans()
		return "(" + ", ".join( str(x) for x in np.nditer(m)) + ")"
	
	def strvector_bool(self, matrix):
		"""Transforms matrix into readable boolean vector."""
		m = matrix.get_matrix_trans()
		return "(" + ", ".join( str(int(x)) for x in np.nditer(m)) + ")"
	
	def base_context(self, request):
		"""Provides the context dictionary created from the taskgrou data for the template."""
		tasks = self.group.ltstask_set.all()
		tasks_data = []
		matrix = tasks[0].matrix.get_matrix_trans()
		
		local_id = 0
		for t in tasks:
			tmp = {}
			tmp['status'] = t.state.get_long_name()
			tmp['id'] = t.id
			local_id += 1
			tmp['local_id'] = local_id
			tmp['algorithm'] = t.algorithm.as_leaf_class().get_long_name()
			pvis = ParamVisitor()
			t.algorithm.as_leaf_class().accept(pvis)
			tmp['params'] = pvis.params
			tmp['date_created'] = t.date_created.isoformat(' ')
			
			tmp['results'] = []
			related_results = t.result_set.all()
			if(related_results):
				tmp['running_time'] = (t.date_finished - t.date_started).total_seconds()
				for r in related_results:
					ttmp =	{}
					ttmp['H'] = r.hParam
					ttmp['residual_sum'] = r.residualSum
					ttmp['vector'] = self.strvector_bool(r.vector)
					ttmp['estimate'] = self.strvector(r.estimate)
					tmp['results'].append(ttmp)
					
			tasks_data.append(tmp)
			
		context = {'matrix': matrix, 'tasks' : tasks_data, 'job_id' : self.group.uuid}
		return context
	
	def render_response(self, request):
		raise NotImplementedError
		
class RendererSimple(RendererBase):
	"""Renders simple template."""
	def render_response(self, request):
		return render(request, 'LTSSummary/summary_simple.html', self.base_context(request))
		
class RendererCompare(RendererBase):
	"""Renders template with compare table."""
	def render_response(self, request):
		return render(request, 'LTSSummary/summary_compare.html', self.base_context(request))
		
class RendererPDF(RendererBase):
	"""Renders PDF from template."""
	
	def render_pdf(self, template_src, context_dict):
		"""Renders tempate and converts it to the pdf."""
		template = get_template(template_src)
		context = Context(context_dict)
		html  = template.render(context)
		result = StringIO.StringIO()
		pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("UTF-8")), result)
		if not pdf.err:
			return http.HttpResponse(result.getvalue(), mimetype='application/pdf')
		return http.HttpResponse("Error Generating PDF! %s" % cgi.escape(html))
	
	def render_response(self, request):
		 return self.render_pdf('LTSSummary/summary_pdf.html', self.base_context(request))

LTSSummary/views/summary.py
from django.http import Http404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from LTSTasks.models import LTSTaskGroup
from LTSTasks.models import LTSTask
from LTSSummary import models as m
from LTSTasks.wizard import WizardEdit

def summary(request, group_id):
	if "_duplicate" in request.POST:
		return duplicate(request, group_id)
	if "_cancel" in request.POST:
		task_id = int(request.POST['_cancel_task'])
		return cancel_task(request, group_id, task_id)
	return render_summary(request, group_id)
		
def render_summary(request, group_id):
	try:
		group = LTSTaskGroup.objects.get(uuid=group_id)
		renderer = m.RendererCompare(group)
		return renderer.render_response(request)
	except LTSTaskGroup.DoesNotExist:
		raise Http404
	
def summary_pdf(request, group_id):
	try:
		group = LTSTaskGroup.objects.get(uuid=group_id)
		renderer = m.RendererPDF(group)
		return renderer.render_response(request)
	except LTSTaskGroup.DoesNotExist:
		raise Http404
		
def cancel_task(request, group_id, task_id):
	try:
		group = LTSTaskGroup.objects.get(uuid=group_id)
		task = group.ltstask_set.get(id=task_id)
		task.cancel()	
		return HttpResponseRedirect(reverse('ltssummary:summary', args=(group_id,)))
	except (LTSTaskGroup.DoesNotExist, LTSTask.DoesNotExist):
		raise Http404
		
def duplicate(request, group_id):
	try:
		group = LTSTaskGroup.objects.get(uuid=group_id)
		WizardEdit().prepare_data(request, group)
		return HttpResponseRedirect(reverse('ltstasks:wizard_edit', args=('start',)))		
		
	except LTSTaskGroup.DoesNotExist:
		raise Http404
	

LTSSummary/templates/LTSSummary/summary_compare.html
{% extends "FITLTS/base.html" %}

{% block content-inner %}
<h1>Result summary for job {{ job_id }} </h1>
<form action="" method="post" {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>{% csrf_token %}
	<div class="form-control">
		<input id="form-duplicate" class="form-button" type="submit" value="Duplicate job" name="_duplicate" />
		<a href={% url 'ltssummary:pdf' job_id %} class="form-button pdf-button">Export as PDF</a>
	</div>
</form>



{% block tasks-summary-matrix %}
<div class="mat_summary">
   <h2>Transformed matrix</h2>
   <div class="scroll_table">
   <table class="scroll_area">
	 <thead>
		 <tr>
			 <th class="row_num"></th>
			 {% for num in matrix.0 %}
			 <th>{{ forloop.counter0 }}</th>
			 {% endfor %}
		 </tr>
	 </thead>
	 <tbody>
	 {% for row in matrix %}
		 <tr>
		 <td class="row_num">{{ forloop.counter0 }}</td>
		 {% for num in row %}
			 <td>{{ num }}</td>
		 {% endfor %}
		 </tr>
	 {% endfor %}
	 </tbody>
   </table>
   </div>
</div>
{% endblock %}

{% block tasks-summary-table %}
<div class="result_summary">
   <h2>Algorithm comparison</h2>
   <table class="result_table">
	 <thead>
		 <tr>
			 <th class="alg_column">Algorithm</th>
			 <th>H</th>			 
			 <th>Time [s]</th>
			 <th>Residual sum</th>
		 </tr>
	 </thead>
	 <tbody>
	 {% for t in tasks %}
	 {% for r in t.results %}
		 <tr>
		 <td class="alg_column">{{ t.algorithm }}</td>
		 <td>{{ r.H }}</td>		 
		 <td>{% if t.running_time %}{{ t.running_time }}{% endif %}</td>
		 <td>{{ r.residual_sum }}</td>
		 </tr>
	 {% endfor %}
	 {% endfor %}
	 </tbody>
   </table>
</div>
{% endblock %}

{% block tasks-summary-list %}
{% for t in tasks %}
   <div class="task_summary">
	  <h2 id="task_{{ t.local_id }}" class="task_header">{{ t.local_id }}</h2>
  
	  <div class="state_block">
		 <h3 class="state_header">Summary:</h3>
		 <dl class="task_state">
			<dt>State</dt><dd>{{ t.status }}</dd>
			<dt>Date created</dt><dd>{{ t.date_created }}</dd>
			{% if t.running_time %}<dt>Running time</dt><dd>{{ t.running_time }} sec.</dd>{% endif %}
		 </dl>
	  </div>
	  
	  <div class="parameter_block">
		 <h3 class="summary_header">Parameters:</h3>
		 <dl class="param_list">
			<dt>Algorithm</dt><dd>{{ t.algorithm }}</dd>
		 {% for p in t.params %}
			<dt>{{ p.name }}</dt><dd>{{ p.value }}</dd>
		 {% endfor %}
		 </dl>
	  </div>
	  
	  <div class="result_block">
	  {% for r in t.results %}
		 <h3 class="summary_header">Result for H = {{ r.H }}</h3>
		 <dl class="result_list">
			<dt>Sum of residuals</dt><dd>{{ r.residual_sum }}</dd>
			<dt>Vector of measurements</dt><dd>{{ r.vector }}</dd>
			<dt>Estimate</dt><dd>{{ r.estimate }}</dd>
		 </dl>
	  {% endfor %}
	  </div>
		
	  <form action="" method="post" {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>{% csrf_token %}
			<div class="form-control">
			<input id="form-cancel-{{ forloop.counter0 }}" class="form-button form-cancel" type="submit" value="Cancel this task" name="_cancel" />
			<input type="hidden" name="_cancel_task" value="{{ t.id }}"/>
			</div>
		</form>
   </div>
{% endfor %}         
{% endblock %}
{% endblock %}

LTSSummary/templates/LTSSummary/summary_pdf.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<style type="text/css">
	@page {
		size: ;
		margin: 1cm;
		@frame footer {
    		    -pdf-frame-content: footerblock;
    		    bottom: 1cm;
    		    margin-left: 1cm;
    		    margin-right: 1cm;
				margin-top: 1cm;
    		    height: 1cm;
		}
	}
	
	p {
		margin:	0;
	}
	
	h2, h3 {
		margin-bottom: 0;
	}
	
	.indent {
		margin-left:	1em;
	}
</style>
</head>
<body>

<div>
	<h1>Result summary for job {{ job_id }} </h1>
	{% for t in tasks %}
	<div class="task_block">
		<h2 id="task_{{ t.local_id }}" class="task_header">{{ t.local_id }}</h2>
		<h3 class="state_header">Summary:</h3>
		<div class="indent">
			<p><strong>Date created:</strong> {{ t.date_created }}</p>
			{% if t.running_time %}<p><strong>Running time:</strong> {{ t.running_time }} sec.</p>{% endif %}
		</div>
	  
		<h3 class="summary_header">Parameters:</h3>
		<div class="indent">
			<p><strong>Algorithm:</strong> {{ t.algorithm }}</p>
			{% for p in t.params %}
				<p><strong>{{ p.name }}:</strong> {{ p.value }}</p>
			{% endfor %}
			</dl>
		</div>
	  
		{% for r in t.results %}
		<h3 class="summary_header">Result for H = {{ r.H }}</h3>
		<div class="indent">
			<p><strong>Sum of residuals:</strong> {{ r.residual_sum }}</p>
			<p><strong>Vector of measurements:</strong> {{ r.vector }}</p>
			<p><strong>Estimate:</strong> {{ r.estimate }}</p>
		</div>
		{% endfor %}
		<hr />
	</div>
	{% endfor %}         
</div>

<div id="footerblock">
    <pdf:pagenumber>
</div>
</body>
</html>

LTSSummary/templates/LTSSummary/summary_simple.html
{% extends "LTSSummary/summary_compare.html" %}

{% block tasks-summary-table %}
{% endblock %}