FITLTS/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from django.contrib import admin

import LTSFactories
import views

# load on startup
admin.autodiscover()
LTSFactories.setup_module() 

urlpatterns = patterns('',
	url(r'^index/$', views.home_page, name='home_page'),
	url(r'^calculator/$', views.calculator_page, name='calculator_page'),
	url(r'^calculator/', include('LTSTasks.urls', namespace='ltstasks')),
	url(r'^overview/$', views.alg_overview_page, name='alg_overview_page'),
	url(r'^library/$', views.library_page, name='library_page'),	
	url(r'^summary/', include('LTSSummary.urls', namespace='ltssummary')),
#	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^/?$', RedirectView.as_view(url=reverse_lazy('home_page'))),
)

LTSTasks/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView

from LTSTasks import views

urlpatterns = patterns('',
	url(r'^new/(?P<step_id>[A-Za-z0-9_-]+)$', views.wizard_new, name='wizard_new'),
	url(r'^edit/(?P<step_id>[A-Za-z0-9_-]+)$', views.wizard_edit, name='wizard_edit'),
)

FITLTS/views/pages.py
from django.shortcuts import render

def home_page(request):
	return render(request, 'FITLTS/home.html', {})
	
def calculator_page(request):
	return render(request, 'FITLTS/calculator/new.html', {})
	
def alg_overview_page(request):
	return render(request, 'FITLTS/alg_overview.html', {})
	
def library_page(request):
	return render(request, 'FITLTS/cpplibrary.html', {})

FITLTS/templates/FITLTS/calculator/done.html
{% extends "FITLTS/base.html" %}
{% block nav-calc %}<li class="menu_active"><a href="{% url 'calculator_page' %}">LTS Calculator</a></li>{% endblock %}

{% block content-inner %}
<p>Your data has been accepted and queued. You can check the data, duplicate or cancel the tasks on the summary page.</p>
<div id="wizard_link"><a  href="{{ group_url }}">View summary</a></div>
{% endblock %}

FITLTS/templates/FITLTS/calculator/new.html
{% extends "FITLTS/base.html" %}
{% block nav-calc %}<li class="menu_active"><a href="{% url 'calculator_page' %}">LTS Calculator</a></li>{% endblock %}

{% block content-inner %}
<p>The wizard will lead you through the creation of new task. It will help you input matrix data, specify transformations, algorithms and algorithms parameters. Afterwards the task will be queued in computation queue. The task summary and result will be available to you anytime following the link you will be given at the end of the wizard.</p>
<div id="wizard_link"><a  href="{% url 'ltstasks:wizard_new' 'start' %}">Start wizard here</a></div>
{% endblock %}